release = ["-DCMAKE_BUILD_TYPE=Release"]
debug = ["-DCMAKE_BUILD_TYPE=Debug"]
release_no_lp = ["-DCMAKE_BUILD_TYPE=Release", "-DUSE_LP=NO"]
pybindings = ["-DPYBINDING_LIBRARY=YES", "-DCMAKE_BUILD_TYPE=Release", "-DDISABLE_PLUGINS_BY_DEFAULT=YES", "-DPLUGIN_LANDMARK_CUT_HEURISTIC_ENABLED=YES", "-DPLUGIN_PLUGIN_ASTAR_ENABLED=YES", "-DPLUGIN_PYDOWNWARD_ENABLED=YES"]
pybindings_code_generation = ["-DPYBINDING_CODE_GENERATION=YES", "-DCMAKE_BUILD_TYPE=Release", "-DDISABLE_PLUGINS_BY_DEFAULT=YES", "-DPLUGIN_LANDMARK_CUT_HEURISTIC_ENABLED=YES", "-DPLUGIN_PLUGIN_ASTAR_ENABLED=YES", "-DPLUGIN_PYDOWNWARD_CODE_GENERATION_ENABLED=YES"]
# USE_GLIBCXX_DEBUG is not compatible with USE_LP (see issue983).
glibcxx_debug = ["-DCMAKE_BUILD_TYPE=Debug", "-DUSE_LP=NO", "-DUSE_GLIBCXX_DEBUG=YES"]
minimal = ["-DCMAKE_BUILD_TYPE=Release", "-DDISABLE_PLUGINS_BY_DEFAULT=YES"]

DEFAULT = "release"
DEBUG = "debug"
